// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/netflix-placement/BannerHero.tsx": () => import("../components/mockups/netflix-placement/BannerHero.tsx"),
  "./components/mockups/netflix-placement/GridFirstTile.tsx": () => import("../components/mockups/netflix-placement/GridFirstTile.tsx"),
  "./components/mockups/netflix-placement/SidebarPoster.tsx": () => import("../components/mockups/netflix-placement/SidebarPoster.tsx")
};
